### ISSUE TITLE
TTL file december doesn't seem valid

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/SARS-CoV-2-WikiPathways#4]
When loading the WP SPARQL endpoint, the SARS-CoV-2 data caused errors in Virtuoso. I was not able to find the issue immediately.

**Comment by egonw** [comment]
Works in the latest release. Checked with new instructions in the README: https://github.com/wikipathways/SARS-CoV-2-WikiPathways/blame/master/README.md#L46
